[main]
pad=0x0

[text-bindings]
# TSM session selection and mark shortcuts (U+E001 through U+E012).
\xee\x80\x81=Control+Shift+1
\xee\x80\x82=Control+Shift+2
\xee\x80\x83=Control+Shift+3
\xee\x80\x84=Control+Shift+4
\xee\x80\x85=Control+Shift+5
\xee\x80\x86=Control+Shift+6
\xee\x80\x87=Control+Shift+7
\xee\x80\x88=Control+Shift+8
\xee\x80\x89=Control+Shift+9
\xee\x80\x90=Control+Shift+period
\xee\x80\x91=Control+Shift+0
\xee\x80\x92=Control+Shift+minus
